<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wx_lottery"
 *
 * Auto generated by Extension Builder 2014-02-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Lottery',
	'description' => 'Lottery',
	'category' => 'plugin',
	'author' => 'Roman Leitner',
	'author_email' => 'rl@webaholix.com',
	'author_company' => 'webaholix s.r.o.',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>